import { PublicKey } from "@solana/web3.js";

// --- SOAR Program ---
export const SOAR_PROGRAM_ID = new PublicKey("SoarNNzwQHMwcfdkdLc6kvbkoMSxcHy89gTHrjhJYkk");

// --- Generated by setup-soar.ts on 2026-02-27 ---
export const SOAR_GAME_ADDRESS = new PublicKey("AbWkE4AkiH2ZUXFFo6kxdnaib1N5dFau3pYpa1yVHh3w");
export const SOAR_LEADERBOARD_ADDRESS = new PublicKey("3iAsidtRHtPaUQWeWSBS5wEWzMra9Ztxtcgb19gu9oSc");
export const SOAR_AUTHORITY_PUBKEY = new PublicKey("81xZtihSF6tooLfTs5jguWvXLUpFxtEbPncF9bHGQLwM");

// Achievement addresses — map to our existing achievement IDs in achievement-store.ts
export const SOAR_ACHIEVEMENTS: Record<string, PublicKey> = {
  first_claim: new PublicKey("H4sdtjQ3zUwHvpr4L5Qnj2pQCqjejJ32av2xN93V6458"),
  streak_3: new PublicKey("2sC7N88EiHGkNcvTAZH18VPR922TT9G7mvgseoytDQcd"),
  streak_7: new PublicKey("462WBrdn9XP5VQWzDroBRDp2rGPhtD2ssHgvxj6ymJ9H"),
  streak_14: new PublicKey("3PtnPjDHT4gVY5EAuf4UtjCsXD9ddftGXs4yoofSpb9A"),
  streak_30: new PublicKey("5hXtG23tFnXuhFDhz1XeisPDnBUryfAjvWViJaaKUw41"),
  top_10: new PublicKey("53FMQAFBreCxdDNz5r3F7GveLeeGHvT4kpdqE9Q4t5BE"),
  multi_block: new PublicKey("9C7utGGDzbAD4kmV1d5KJagQs2bTMB4Yxr9SKstw5oZZ"),
};

// HACKATHON ONLY: Authority keypair for client-side score submission.
// In production, move to server-side behind POST /api/soar/score.
// This key only controls a SOAR game registration (no funds at risk).
export const SOAR_AUTHORITY_SECRET = new Uint8Array([
  182, 163, 51, 43, 216, 80, 114, 161, 135, 242, 191, 30, 168, 241, 28, 79,
  194, 130, 130, 202, 43, 146, 247, 114, 134, 177, 65, 118, 79, 150, 222, 249,
  104, 64, 163, 110, 95, 83, 40, 196, 224, 206, 180, 222, 93, 70, 38, 94,
  183, 98, 143, 200, 98, 48, 164, 213, 75, 106, 203, 133, 40, 81, 166, 4,
]);

// Whether SOAR integration is active
export const SOAR_ENABLED = true;
